### ISSUE TITLE
check conductivity values

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-osd74-crate#4]
In the water log sheets, check the conductivity values. 
In some cells there is the unit too. 
Others seem emormously high. 

@melinalou

**Comment by melinalou** [comment]
those are the two values appeared, no unit.
9642.9
31.63

**Comment by cpavloud** [comment]
@melanthia you should contact the providers, it seems that one of these values is wrong. 
@melinalou maybe the units are corrected in the google spreadsheets but they were not re-harvested to Github so the issue still appears in the .csv files

**Comment by melinalou** [comment]
Please can you check if it still appears.
the .csv you referring to are not those?https://drive.google.com/drive/folders/1J-_ixCYmIuE_kFQ2tMEpmJ4TJj8xfxG2

**Comment by cpavloud** [comment]
The units are not included in the [google spreadsheet](https://docs.google.com/spreadsheets/d/1VATpzmhwmk8sYkhEjCbDUZHRiYuNGpSRefhXthZRbfQ/edit?gid=15718907#gid=15718907), ok. 
So, we just need to confirm that the values are correct.

**Comment by melinalou** [comment]
confirmed
